//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestionDespacho.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actuaciones
    {
        public int ActuacionId { get; set; }
        public int ExpedienteId { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Tipo { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Expedientes Expedientes { get; set; }
    }
}
