//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestionDespacho.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        public int CitaId { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<int> ExpedienteId { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string Lugar { get; set; }
        public string Motivo { get; set; }
        public string Estado { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Expedientes Expedientes { get; set; }
    }
}
