//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestionDespacho.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expedientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expedientes()
        {
            this.Actuaciones = new HashSet<Actuaciones>();
            this.Citas = new HashSet<Citas>();
        }
    
        public int ExpedienteId { get; set; }
        public string Codigo { get; set; }
        public int ClienteId { get; set; }
        public int EstadoId { get; set; }
        public string Tipo { get; set; }
        public System.DateTime FechaApertura { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actuaciones> Actuaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Citas> Citas { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual EstadosExpediente EstadosExpediente { get; set; }
    }
}
